# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine

RUN apk add --no-cache libc6-compat \
    && addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci --ignore-scripts \
    && npm rebuild \
    && ./node_modules/.bin/prisma generate \
    && chown -R nextjs:nodejs /app

COPY --chown=nextjs:nodejs src ./src
COPY --chown=nextjs:nodejs public ./public
COPY --chown=nextjs:nodejs messages ./messages
COPY --chown=nextjs:nodejs next.config.mjs tsconfig.json postcss.config.mjs components.json tanstack.d.ts ./

USER nextjs

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

EXPOSE 5555
EXPOSE 3000

CMD ["npm", "run", "dev"]
