GCP_PROJECT_ID: "echomori-app"
GCP_REGION: "europe-west1"
GCP_ARTIFACT_REPO: "echomori"
GCP_RUN_SA: "echomori-run@echomori-app.iam.gserviceaccount.com"
GCP_BUCKET_NAME: "echomori-drive-bucket-prod"

NEXT_PUBLIC_APP_NAME: "Echomori"
NEXT_PUBLIC_APP_URL: "https://echomori.fr"
NEXT_PUBLIC_SUPPORT_MAIL: "hello@echomori.fr"
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyBZRCopl6dpWzPcy90-MYY9BPSnF-ewK4s"
NEXT_PUBLIC_USER_MAP_ID: "b9289b97f53f2f9fcc275ca9"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51RPVJcDAIViosHG27ZQvBePD1tyrPPogwPmD2XexxOrTg8o0QtHsMYb9ruZjS5z9FTpQ3pBOYGUvaI9QrXEW6e5K00MXe59QpS"
NEXT_PUBLIC_PRICING_FREE_MONTHLY: "price_1RimXVDAIViosHG2BupcTCn7"
NEXT_PUBLIC_PRICING_FREE_YEARLY: "price_1RimXkDAIViosHG2VG4SbdOP"
NEXT_PUBLIC_PRICING_EFFICIENT_MONTHLY: "price_1RilCWDAIViosHG2UgLPnE8d"
NEXT_PUBLIC_PRICING_EFFICIENT_YEARLY: "price_1RilCqDAIViosHG2tQC4g9Tr"
NEXT_PUBLIC_PRICING_PRO_MONTHLY: "price_1RilEDDAIViosHG2gdTv3s8Z"
NEXT_PUBLIC_PRICING_PRO_YEARLY: "price_1RPVaQDAIViosHG2DEsyQXEc"

MAIL_HOST: "ssl0.ovh.net"
MAIL_PORT: "587"
MAIL_SECURE: "false"
MAIL_SENDER: "hello@echomori.fr"
OAUTH_GOOGLE_CLIENT_ID: "455489553359-o19bevs2nlkpnf2lge4o02ct38ng68ks.apps.googleusercontent.com"
