-- AlterTable
ALTER TABLE "user" ALTER COLUMN "usedStorage" SET DEFAULT 0,
ALTER COLUMN "usedStorage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maxStorage" SET DEFAULT 5000,
ALTER COLUMN "maxStorage" SET DATA TYPE DOUBLE PRECISION;
