name: CD Flow

on:
  push:
    branches: [ main ]

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect, pull, build and deploy
        run: |
          ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIRECTORY }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && npm i && npx prisma migrate deploy && npx prisma generate && npm run build && sudo systemctl restart echomori.service"
      - name: Cleanup
        run: rm -rf ~/.ssh
