name: CD Flow

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-cloud-run.yml
    with:
      service: echomori
      environment_name: production
      config_file: infra/cloudrun.production.yaml
    secrets: inherit
