name: Staging CD Flow

on:
  push:
    branches: [ staging ]

jobs:
  run_pull:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Connect, pull, build and deploy
        run: |
          ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIRECTORY }} && sudo systemctl stop echomori-staging.service && git checkout ${{ secrets.STAGING_BRANCH }} && git pull && npm i && npx prisma migrate deploy && npx prisma generate && npm run build && sudo systemctl start echomori-staging.service"
      - name: Cleanup
        run: rm -rf ~/.ssh
