# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Check NextJs build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "staging"]
    
  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]

env:
  NODE_ENV: production
  GOOGLE_BUCKET_NAME: ${{ secrets.GOOGLE_BUCKET_NAME }}
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  # Build job
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Clear .next cache
        run: rm -rf .next
      - name: Install dependencies
        run: npm install
      - name: Debug missing files
        run: |
          find src/components -iname 'header.tsx'
      - name: Build with Next.js
        run: npm run build