name: Next.js CI/CD

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main, staging ]

env:
  NEXT_PUBLIC_APP_NAME: "Echomori"
  NEXT_PUBLIC_APP_URL: "http://localhost:3000"
  NEXT_PUBLIC_SUPPORT_MAIL: "hello@echomori.fr"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  GCP_BUCKET_NAME: ${{ secrets.GOOGLE_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build